### ISSUE TITLE
Collection of tools

### ISSUE THREAD

**Issue by tomek-he-him** [npm-scripts/scripts#11]
How about creating a list of generic, platform-independent tools to use in npm scripts? My candidates:
- [cpy](http://npm.im/cpy)
- [mkdirp](http://npm.im/mkdirp)
- [mve](http://npm.im/mve)
- [posix-cat](http://npm.im/posix-cat)

**Comment by stoeffel** [comment]
:+1: 
May be related to this https://github.com/npm-scripts/meta/issues/3

**Comment by hemanth** [comment]
Big :+1:

**Comment by stoeffel** [comment]
Do you guys agree that we add an array `dependencies` to each script. so we can later use it in a cli to install the deps? Do you think we need the version too?

**Comment by stoeffel** [comment]
IMO the deps only contain npm deps not git and other deps.

**Comment by tomek-he-him** [comment]
:+1:

We definitely need a version.
